post_install() {
	SERVERNAME=$(hostname -s)
	sed -i "s/__BASENAME__/${SERVERNAME}/g" /etc/bacula/bacula-sd.conf
	post_upgrade
}

post_upgrade() {
	getent group bacula >/dev/null || groupadd -r bacula
	getent passwd bacula-sd >/dev/null || useradd -r -g bacula -d / -s /sbin/nologin -c "Bacula storage daemon user" bacula-sd
}

post_remove() {
	getent passwd bacula-sd >/dev/null && userdel bacula-sd || true
	getent group bacula >/dev/null && (groupdel bacula || true) || true
}
